### ISSUE TITLE
Github hosted ?

### ISSUE THREAD

**Issue by JalilArfaoui** [small-tech/nodekit#7]
Thank you for working on this small tech project.

I’m honestly curious why centralized, GAFAM owned and for-profit Github was chosen to host this project source and lifecycle ?

**Comment by aral** [comment]
Because we don’t have the resources to or desire to host people on our self-hosted GitLab instance (https://source.small-tech.org). 

My goal is to have repositories hosted on our own personal small web sites in the future. So I’m not going to devote any more time and effort to a half-way solution that gets us none of the benefit of truly independent repositories hosted in a small web fashion where we can still collaborate with others who have their own small web sites without requiring user accounts on our own server.

Case in point: you would have had to create an account on our GitLab server to open this issue there. Since we don’t allow new user registrations – because we don’t want to become a centralised hub ourselves – you wouldn’t have been able to open this issue and express your thoughts there.

**Comment by JalilArfaoui** [comment]
Thanks for your response @aral …

I'm curious to see what solution you want to implement in the future that permit repo collaboration without having to host people …
